// Copyright © 2019 SpotHero, Inc. All rights reserved.

#if !canImport(ObjectiveC)
    import XCTest

    extension HTTPStatusCodeTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__HTTPStatusCodeTests = [
            ("testResponseTypes", testResponseTypes),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(HTTPStatusCodeTests.__allTests__HTTPStatusCodeTests),
        ]
    }
#endif
