// Copyright © 2019 SpotHero, Inc. All rights reserved.

#if !canImport(ObjectiveC)
    import XCTest

    extension MockServiceTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__MockServiceTests = [
            ("testStubbingAllRequests", testStubbingAllRequests),
            ("testStubbingExactURLOnly", testStubbingExactURLOnly),
            ("testStubbingGetFailsPostRequests", testStubbingGetFailsPostRequests),
            ("testStubbingHostOnly", testStubbingHostOnly),
            ("testStubbingPathOnly", testStubbingPathOnly),
            ("testStubbingQueryOnlyFails", testStubbingQueryOnlyFails),
            ("testStubbingSameURL", testStubbingSameURL),
            ("testStubbingSchemeOnlyFails", testStubbingSchemeOnlyFails),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(MockServiceTests.__allTests__MockServiceTests),
        ]
    }
#endif
