name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  PACKAGE_NAME: UtilityBelt
  XCODEBUILD_WORKSPACE: UtilityBelt.xcworkspace
  XCODEBUILD_SCHEME: UtilityBelt
  DEVELOPER_DIR: /Applications/Xcode_11.4.1.app/Contents/Developer

jobs:
  iOS:
    name: ${{ matrix.device_name }} - iOS ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      matrix:
        device_name: ["iPhone 11 Pro"]
        os: ["13.4.1"]
        # The keys below are included as a one-off combination
        include:
          - device_name: "Apple TV 4K"
            os: "latest"
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "$XCODEBUILD_WORKSPACE" -scheme "$XCODEBUILD_SCHEME" -destination "name=${{ matrix.device_name }},OS=${{ matrix.os }},platform=iOS Simulator" clean test | xcpretty
  macOS:
    name: macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "$XCODEBUILD_WORKSPACE" -scheme "$XCODEBUILD_SCHEME" -destination "platform=macOS" clean test | xcpretty
  tvOS:
    name: ${{ matrix.device_name }} - tvOS ${{ matrix.os }}
    runs-on: macos-latest
    strategy:
      matrix:
        device_name: ["Apple TV 4K"]
        os: ["13.4"]
    steps:
      - uses: actions/checkout@v2
      - name: Test ${{ matrix.destination }}
        run: set -o pipefail && env NSUnbufferedIO=YES xcodebuild -workspace "$XCODEBUILD_WORKSPACE" -scheme "$XCODEBUILD_SCHEME" -destination "name=${{ matrix.device_name }},OS=${{ matrix.os }},platform=tvOS Simulator" clean test | xcpretty
  # spm:
  #   name: Test with SPM
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: SPM Test
  #       run: swift test -c debug
